In [3]:
# PROBABILITY SECTION
# problem definition:
# '''
#     INPUT: FLOAT (probability of drawing a chocolate cooking from Jar A),
#             FLOAT (probability of drawing a chocolate cooking from Jar B)
#     OUTPUT: FLOAT (conditional probability that cookie was drawn from Jar A
#                    given that a chocolate cookie was drawn)
#     There are two jars of cookies.
#     Each has chocolate and peanut butter cookies.
#     INPUT 'a' is the fraction of cookies in Jar A which are chocolate
#     INPUT 'b' is the fraction of cookies in Jar B which are chocolate
#     A jar is chosen at random and a cookie is drawn.
#     The cookie is chocolate.
#     Return the probability that the cookie came from Jar A.
#     '''

def cookie_jar(a, b):
    a_chocolate=a
    jar_a=0.5
    tot_choc=a+b
    return round((a/tot_choc)*0.5, 2)
    
    

In [4]:
cookie_jar(0.3, 0.6)

0.17

In [21]:
# NumPy SECTION
'''
    INPUT: INT, INT, INT, NUMPY ARRAY
    OUTPUT: NUMPY ARRAY
    (of matrix product of r-by-c matrix of "scalar"'s time matrixA)
    Create matrix of size (rows, cols) with elements initialized to the scalar
    value. Right multiply that matrix with the passed matrixA (i.e. AB, not
    BA).  Return the result of the multiplication.  You needn't check for
    matrix compatibililty, but you accomplish this in a single line.
    E.g., array_work(2, 3, 5, [[3, 4], [5, 6], [7, 8]])
           [[3, 4],      [[5, 5, 5],
            [5, 6],   *   [5, 5, 5]]
            [7, 8]]
    '''

def array_work(rows, cols, scalar, matrixA):
    B=np.array([scalar]*(2*3)).reshape(2,3)
    return np.matmul(matrixA, B)
    

In [22]:
array_work(2, 3, 5, [[3, 4], [5, 6], [7, 8]])

array([[35, 35, 35],
       [55, 55, 55],
       [75, 75, 75]])

In [15]:
#To convert a scalar into a numpy matrix given rows and columns
np.array([5]*6).reshape(2,3)

array([[5, 5, 5],
       [5, 5, 5]])

In [110]:
#More numpy: problem definition:
# '''
#     INPUT: NUMPY ARRAY, INT
#     OUTPUT: NUMPY ARRAY
#     (of just elements in "arr" greater or equal to "minimum")
#     Return an array of only the elements of "arr" that are greater than or
#     equal to "minimum"
#     Ex:
#     In [1]: boolean_indexing([[3, 4, 5], [6, 7, 8]], 7)
#     Out[1]: array([7, 8])
#     '''
def boolean_indexing(arr, minimum):
    res=[]
    for i in range(len(arr)):
        if minimum in arr[i]:
            for j in arr[i]:
                if j>=minimum:
                    res.append(j)        
    return np.array(res)
                

In [111]:
boolean_indexing([[3, 4, 5], [6, 7, 8]], 6)

array([6, 7, 8])

In [117]:
# Pandas SECTION

'''
    INPUTS: INT, INT, LIST (of length "length")
    OUTPUT: PANDAS SERIES (of "length" sequential integers
             beginning with "start" and with index "index")
    Create a pandas Series of length "length" with index "index"
    and with elements that are sequential integers starting from "start".
    You may assume the length of index will be "length".
    E.g.,
    In [1]: make_series(5, 3, ['a', 'b', 'c'])
    Out[1]:
    a    5
    b    6
    c    7
    dtype: int64
    '''

def make_series(start, length, index):
    import pandas as pd
    ans=[]
    for i in range(length):
        ans.append(start)
        start+=1
    return pd.Series(ans, index)
    

In [118]:
make_series(5, 3, ['a', 'b', 'c'])

a    5
b    6
c    7
dtype: int64

In [119]:
'''
    INPUT: DATAFRAME, STR, STR, STR
    OUTPUT: None
    Insert a column (colC) into the dataframe that is the sum of colA and colB.
    Assume that df contains columns colA and colB and that these are numeric.
    '''
def data_frame_work(df, colA, colB, colC):
    import pandas as pd
    df[colC]=df[colA]+df[colB]