In [ ]:
The idea is to avoid loops and vectorize computations

The purpose of this exercise is to speed up the code in Exercise 2: Compute a probability by vectorization.

Hint. For an array r of uniformly distributed random numbers on [0,1), make use of r1 = r[r>0.5] and r1[r1<0.6]. 
An alternative is numpy.where combine with a compound boolean expression with numpy.logical_and(0.5>=r, r<=0.6). 
                                                                 
                                                                 
                                                                 

In [18]:
import random
import numpy as np
import operator as op

arr=np.random.uniform(size=1000000)
condition=op.and_(0.5>=arr, arr<=0.6)
condition

array([ True, False, False, ...,  True, False, False])

In [19]:
arr

array([0.23350901, 0.94662293, 0.60595385, ..., 0.06537547, 0.63017846,
       0.70331602])

In [20]:
This .size method only provides the number of True conditions

print(arr[condition].size)

499898


In [28]:
To count the number of true conditions 

np.size(np.where(condition==True))

499898

In [23]:
Another way to count the conditions

unique, counts = np.unique(condition, return_counts=True)

In [24]:
counts

array([500102, 499898])