In [ ]:
Explain the relevant syntax in Python. Define relevant key terms.

Python has two primary loop structures:
For
While 


In [ ]:
For Loop
A for loop is used for iterating over a sequence 
(that is either a list, a tuple, a dictionary, a set, or a string. Note: these are also called data structures). 

This is less like the ‘for’ keyword in other programming languages and works more like an iterator 
(meaning that helps to iterate over something) method.


In [3]:
Introducing for loop to iterate a given data structure and usage of 'if' clause

Let’s count the number of alphabet ‘a’ in the given string, s.

s='abhgaaaanhgtyaajmaafagaiahaaaraeaaawa'

count_value=0
for i in s:
    if i=='a':
        count_value+=1
print(count_value)
    

20


In [9]:
Iterating for a certain number of times

Let us assume that for every hour of binge watching we lose $10 (hello, which world are we in :)). So we would like 
to know how much money would we be left with after 20 hours of binge watching our favorite show on Netflix.

remaining_cost=1000

for item in range(20):
    remaining_cost-=10
    
print(remaining_cost)
    

800


In [13]:
Iterating over a sequence and creating a dictionary

A dictionary is another data structure. It’s also called a hash table. 
A high level of the dictionary:

Dictionaries are used to store data values in key: value pairs. A dictionary is a collection that is unordered, 
changeable, and does not allow duplicates. Dictionaries are written with curly brackets:

Example:
thisdict = {"brand": "Ford","model": "Mustang","year": 1964}

Where thisdict is the name of the dictionary
"Brand", "model", and "year" are the keys
"Ford", "Mustang", 1964 are the values

Now let’s see an illustration where we iterate over a list of cutlery items and create a dictionary of those 
items using a for loop.



Determine how many cutleries do we have in the given list and store them in a dictionary

d={}
cutlery = ["plate", "spoon", "fork", "silver fork", "golden plate", "silver plate", "silver spoon", "wooden plate"]
for x in cutlery:
    if 'plate' in x:
        d['plate']=d.get('plate', 0)+1
    if 'spoon' in x:
        d['spoon']=d.get('spoon', 0)+1
    if 'fork' in x:
         d['fork']=d.get('fork', 0)+1
        
print(d)
    
        
    

{'plate': 4, 'spoon': 2, 'fork': 2}


In [14]:
Use of 'break' statement in a for loop

The Python 'break' statement immediately terminates a loop entirely. Program execution proceeds to the first 
statement following the loop body.


Lets consider a simulating situation where we draw numbers from a range until the limit 5000. When it reaches 
the limit,the program execution gets out of the loop in this context as we have the values iterated as the 
limit in the if statement.


total=0
for val in range(100000):
    if val == 5000:
        break
    else:
        total+=val

print(total)


12497500


In [15]:
Program to show the use of ‘continue’ statement inside a for loop

The Python ‘continue’ statement immediately terminates the current loop iteration. Execution jumps to the top of the 
loop, and the controlling expression is re-evaluated to determine whether the loop will execute again or terminate.


Lets just say we ought to avoid printing "i" from a word "string". Here the continue statement has skipped the 
rest of the code inside the loop for the iteration where the if statement is true, i.e., if val=='i'. 
The loop then continues with the rest of the characters in "string".


for val in "string":
    if val == "i":
        continue
    print(val)

print("The end")


s
t
r
n
g
The end


In [25]:
Demonstrating the use of nested loops
Nested loops are literally a loop within a loop. Most often we use such loops to fill in a matrix or iterate over two 
lists or other sequences. The point to be noted is the time complexity of such nested loops. For now, let’s have in 
mind that nested for loops going to take more time compared to a single for loop. 

In programming terminology, we call it O(N) for a single loop i.e., pronounced as O of N, where N represents the 
length of a sequence like a list. 

So nested for loops take O(N^2), i.e., pronounced as O of N squared, where N represents the length of a sequence 
like a list. 


Shall we count how many number of nickels, quarters, and dimes are there in a bag of coins?


bag_of_coins = [[.10, .10, 0.05],[0.05,0.75, 0.65],[0.9, 0.8, 0.75, 0.75]]

nickel, quarter, dime=0, 0, 0

for coin in bag_of_coins:
    for item in coin:
        if item==0.05:
            nickel+=1
        if item==0.75:
            quarter+=1
        if item==0.10:
            dime+=1
            
print("The total number of nickels is {}".format(nickel))
print("The total number of quarter is {}".format(quarter))
print("The total number of dime is {}".format(dime))

The total number of nickels is 2
The total number of quarter is 3
The total number of dime is 2


In [22]:
Nested for loops to fill in a matrix

import numpy as np
dp = np.zeros((3,4))

for i in range(3):
    for j in range(4):
        dp[i][j]=1
print(dp)
        

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
While Loop
With the loop, we can execute a set of statements as long as a condition is true.


In [26]:
Shall we buy items worth $20 given the fact that we already have bought an item worth $10, so our cost=$10 and 
buy_items=1?

We are constrained to keep buying items as long as the cost remains less than $100  

buy_items = 1
cost=10
while cost < 100:
    buy_items+=1
    cost+=20
    
print(buy_items)

Note: remember to increment cost (i.e., every iteration by $20), or else the loop will continue forever.


6


In [28]:
Use of break statement inside the while loop

With the ‘break’ statement we can stop the loop even if the while condition is true.

Exit the loop when i is 3. 

i = 1
while i < 6:
    print(i)
    if i == 3:
        break
    i+=1


1
2
3


In [29]:
Using  ‘continue’ statement with a while loop:

    With the ‘continue’ statement we can stop the current iteration and continue with the next.

In this example, we intend to decrement the values of n. Except 2 we are interested in all other values of n. 
Here is where the continue statement comes in handy.

n = 5
while n > 0:
    n -= 1
    if n == 2:
        continue
    print(n)
print('Loop ended.')


4
3
1
0
Loop ended.


In [30]:
Using  ‘continue’ statement with a while loop:

With the ‘continue’ statement we can stop the current iteration and continue with the next.

As long as while condition is satisfied the body within the while loop is executed. When the condition is not
met then the else statement is executed.

fruits = ["banana", "apple", "orange", "kiwi"]
position = 0
while position < len(fruits):
    print(fruits[position])
    position = position + 1
else:
    print("reached end of list")
    
    

banana
apple
orange
kiwi
reached end of list


In [31]:
Nested while loop

When a while loop is present inside another while loop then it is called nested while loop. Lets take an example to 
understand this concept.


i = 1
j = 5
while i < 4:
    while j < 8:
        print(i, ",", j)
        j = j + 1
        i = i + 1

1 , 5
2 , 6
3 , 7


In [36]:
Write a Python program which iterates the integers from 1 to 16. For multiples of three print "Fizz" instead of the 
number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print 
"FizzBuzz". Use for loop to construct your code.
------------------------------------------------------------------------------------------------------------------------
solution
for element in range(16):
    if element % 3 == 0 and element % 5 == 0:
        print("fizzbuzz")
    if element % 3 == 0:
        print("fizz")
    if element % 5 == 0:
        print("buzz")
    else:
        print(element)

------------------------------------------------------------------------------------------------------------------------
Hint:
1. Use the modulo function % (modulo function provides the remainder of a division operation) to check if a number is 
divided by 3, 5, or 15

2. 15 is divided by 3, 5, and 15. So if you check the condition whether a number in the range is divided by 3 first 
and secondly by 5 you will never get to check the condition whether the number is divided by 15.

fizzbuzz
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz


In [38]:
for element in range(16):
    if element % 3 == 0 and element % 5 == 0:
        print("fizzbuzz")
        continue
    if element % 3 == 0:
        print("fizz")
        continue
    if element % 5 == 0:
        print("buzz")
        continue
    else:
        print(element)

fizzbuzz
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz


In [39]:
Write a Python program to print the Fibonacci series between 0 to 50. Write your code using while loop.

Note : The Fibonacci Sequence is the series of numbers :
0, 1, 1, 2, 3, 5, 8, 13, 21, ....

Every next number is found by adding up the two numbers before it. 
------------------------------------------------------------------------------------------------------------------------
solution:

x,y=0,1

while y<50:
    print(y)
    x,y = y,x+y
    
------------------------------------------------------------------------------------------------------------------------
Hint:
1. Think of assigning y to x and x+y to y. Bonus points if you do the assignment effectively in one line


1
1
2
3
5
8
13
21
34
